In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x) # One dimensional array
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype # Type of elements in that array

dtype('int32')

In [4]:
x.shape # Returns the dimensions of the array (rows and columns) --> this is a rank 1 array

(5,)

In [13]:
y = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]) # this is a rank 2 array
print(y)
y.shape

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


(5, 3)

In [15]:
y.size

15

In [17]:
x = np.array([1, 'Hello', 'World'])
print(x)

['Hello' 'World']


In [20]:
print('shape:',  x.shape)
print('type:', type(x))
# If you try to create arrays with multiple types, numpy will convert it all to a single type
print('dtype:', x.dtype) # Unicode strings of 5 characters 

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [22]:
x = np.array([1, 2, 3.1])
print(x, x.dtype) # up-casting

[1.  2.  3.1] float64


In [25]:
# We can set a type manually and NumPy will cast it for us
x = np.array([1.4, 1.2, 1.2], dtype=np.int64)
print(x)
print('dtype:', x.dtype)

[1 1 1]
dtype: int64


In [27]:
x = np.array([1,2,3,4,5])
# This saved the array into a file called my_array.npy
np.save('my_array', x)

In [28]:
X = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
