In [6]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
# Numpy array of 0s
X = np.zeros((3, 4)) # Takes the shape of the array you want to create
print(X)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
X = np.full((4, 3), 5) # lines and columns
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [12]:
print(X.dtype)

int32


In [13]:
X = np.eye(5) # main diagnol filled with one
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
X = np.diag([10, 20, 30, 50])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [16]:
X = np.arange(10) # range from 0 to 9
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
x = np.arange(1, 20, 4) # start point, stop point, distance between values
print(x)

[ 1  5  9 13 17]


In [24]:
x = np.linspace(0, 25, 10, endpoint=False) # start, stop, and end (fit 10 evenly spaces numbers)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [28]:
# Re shape a vector to a matrix of (4 lines / 5 columns)
# rank 1 to rank 2
x = np.arange(20)
print(x)
x = np.reshape(x, (4, 5))
print(x)
x = np.reshape(x, (10, 2))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [31]:
Y = np.arange(20).reshape((10, 2))
print(Y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [34]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [37]:
# We need to create random matrices when initializing the weights of a 
# neural network

X = np.random.random((3, 3))
print(X)

[[0.9572381  0.28696462 0.32401504]
 [0.75861116 0.11528797 0.58605164]
 [0.68177814 0.38980048 0.21379248]]


In [39]:
X = np.random.randint(4, 15, (3, 2))
print(X)

[[12 12]
 [ 7  5]
 [12 10]]


In [40]:
# Random numbers to have an average of 0
# 1000 by 1000 arrays of random floats of a mean of 0 ()
X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[ 0.00628859  0.11784095 -0.01329309 ...  0.01520725 -0.00645036
   0.1904269 ]
 [ 0.00365581 -0.11379881 -0.08467722 ...  0.04840637  0.13191623
   0.19879669]
 [ 0.11551397  0.29276882 -0.05571813 ...  0.11296809 -0.12571006
   0.01534958]
 ...
 [-0.00486456  0.04197005 -0.01039846 ... -0.05038371  0.03104801
  -0.1180762 ]
 [ 0.15213949  0.02311877 -0.05933455 ...  0.18433967 -0.07905444
   0.08933645]
 [ 0.0763493  -0.07304372  0.1065164  ...  0.03971839  0.14288811
  -0.12665277]]


In [41]:
print('mean:', X.mean())
print('std:', X.std())
print('max:', X.max())
print('min:', X.min())
print('# positive:', (X > 0).sum())
print('# negative:', (X < 0).sum())

mean: 7.023846122713868e-07
std: 0.09996797769985358
max: 0.49634402305962894
min: -0.5064648806934403
# positive: 499688
# negative: 500312


In [57]:
X = np.arange(2, 34, 2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
