In [1]:
import numpy as np

In [2]:
# Boolean indexing 
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
print(X[X > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
print(X[X <= 7])

[0 1 2 3 4 5 6 7]


In [5]:
print(X[(X > 10) & (X < 17)])

[11 12 13 14 15 16]


In [6]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [11]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [13]:
x = np.random.randint(1, 11, size=(10, ))
print(x)

[ 2  4  8 10 10 10  6 10  6  7]


In [15]:
print(np.sort(x))
print(x)

[ 2  4  6  6  7  8 10 10 10 10]
[ 2  4  8 10 10 10  6 10  6  7]


In [18]:
# Sorting changes the original array
x.sort()
print(x)

[ 2  4  6  6  7  8 10 10 10 10]


In [19]:
print(np.sort(np.unique(x)))

[ 2  4  6  7  8 10]


In [21]:
# Sorting rank 2 arrays
# Line and column size
X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 4  5  7  7 10]
 [ 9  2  7  1 10]
 [ 6  8  2  4  4]
 [ 1  2 10  9 10]
 [ 1  2 10  7  6]]


In [22]:
# Sort X by columns
print(np.sort(X, axis=0))

[[ 1  2  2  1  4]
 [ 1  2  7  4  6]
 [ 4  2  7  7 10]
 [ 6  5 10  7 10]
 [ 9  8 10  9 10]]


In [23]:
# Sort X by rows
print(np.sort(X, axis=1))

[[ 4  5  7  7 10]
 [ 1  2  7  9 10]
 [ 2  4  4  6  8]
 [ 1  2  9 10 10]
 [ 1  2  6  7 10]]


In [37]:
X = np.arange(1, 26, 1).reshape(5,5)
print(X[X % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
