In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
# Sum of two arrays
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [9]:
# Arrays must have the same shape, or be broadcastable
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [10]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print(X)

[[1 2]
 [3 4]]


In [11]:
Y = np.array([5, 6, 7, 8]).reshape(2, 2)
print(Y)

[[5 6]
 [7 8]]


In [12]:
# We perform basic element-wise operations using arithmetic symbols and functions
print(X + Y)

[[ 6  8]
 [10 12]]


In [13]:
print(X - Y)

[[-4 -4]
 [-4 -4]]


In [14]:
print(X * Y)

[[ 5 12]
 [21 32]]


In [16]:
print(X / Y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
print(x)

[1 2 3 4]


In [18]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [19]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [20]:
print(np.power(x, 2))

[ 1  4  9 16]


In [21]:
print(X)

[[1 2]
 [3 4]]


In [22]:
print('average of all:', X.mean())

average of all: 2.5


In [24]:
print('average of columns:', X.mean(axis=0))
print('average of rows:', X.mean(axis=1))

average of columns: [2. 3.]
average of rows: [1.5 3.5]


In [26]:
print('sum of all:', X.sum())
print('sum of columns:', X.sum(axis=0))
print('sum of rows:', X.sum(axis=1))

sum of all: 10
sum of columns: [4 6]
sum of rows: [3 7]


In [27]:
# Standard deviation
X.std()

1.118033988749895

In [29]:
np.median(X)

2.5

In [30]:
X.max()

4

In [31]:
X.min()

1

In [32]:
print(X)

[[1 2]
 [3 4]]


In [33]:
# Add 3 to each element like this
print(3 + X)

[[4 5]
 [6 7]]


In [34]:
print(X - 3)
print(X * 3)
print(X / 3)

[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [35]:
Y = np.arange(9).reshape(3,3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
x = np.arange(3)
print(x)

[0 1 2]


In [37]:
# 0 + 0, 1 + 1, 2 + 2
# 0 + 3, 1 + 4, 2 + 5
# ...
# Broadcasting the smaller array along the bigger array
# That way they have compatible shapes
print(Y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [39]:
z = np.arange(3).reshape(3,1)
print(z)

[[0]
 [1]
 [2]]


In [40]:
# Brodcasting to columns
print(z + Y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [41]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.full((4, 4), 0)
Y = np.array([1, 2, 3, 4])
print(X + Y)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
